### ISSUE TITLE
Coupon code for non base currency discount values don't apply the discount

### ISSUE THREAD

**Issue by johnwbaxter** [KuriousAgency/commerce-currency-prices#8]
Hi,

My base currency is GBP.

My current user is from the US so their product is added as USD. Then when they get to checkout and put their discount code in, the discount doesn't apply.

Do I need to set the cart itself to be USD somehow?

Thanks

John

**Comment by mcjackson18** [comment]
@johnwbaxter, there was a bug where the base discount wasn't using the correct currency value, this has now been fixed in 2.5.4.

In answer to your question, yes you will need to set the paymentCurrency on the cart to the customer's selected currency. This can be done in a plugin or module by listening for an event - this will depend on how a customer's currency is selected on your site.

In the event something like this should work.

```
use craft\commerce\Plugin as Commerce;

$cart = Commerce::getInstance()->getCarts()->getCart();

$currency = $newCurrency; //replace $newCurrency, this might be a query or post param
if ($cart->paymentCurrency != $currency) {
     $cart->paymentCurrency = $currency;
     Craft::$app->getElements()->saveElement($cart);
}
```
